sonar.projectKey=marwaboussaha_summer-intership
sonar.organization=marwaboussaha

sonar.sources=backend,frontend/src
sonar.exclusions=backend/sandboxes/**,backend/tests/**,**/node_modules/**,frontend/dist/**

sonar.tests=backend/tests
sonar.test.inclusions=**/*.test.js

# C'est CETTE ligne qui débloque la couverture
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info

sonar.coverage.exclusions=backend/sandbox/template/**,backend/test-groq.js,**/*.config.js,database/**